# Generated by Django 5.2.1 on 2025-06-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='chinese_character',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='word',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='word',
            name='pinyin',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='word',
            name='translation',
            field=models.CharField(max_length=128),
        ),
    ]
